# DESCRIPTION: GitLab CI/CD for libRetro (NOT FOR GitLab-proper)

##############################################################################
################################# BOILERPLATE ################################
##############################################################################

# Core definitions
.core-defs:
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
    CORENAME: dolphin
    CORE_ARGS: -DLIBRETRO=ON
    
# Inclusion templates, required for the build to work
include:
  ################################## DESKTOPS ################################
  # Windows
  - project: 'libretro-infrastructure/ci-templates'
    file: '/windows-cmake-mingw.yml'

  # Linux 64-bit
  - project: 'libretro-infrastructure/ci-templates'
    file: '/linux-cmake.yml'
    
  # MacOS x64
  - project: 'libretro-infrastructure/ci-templates'
    file: 'osx-cmake-x86.yml'

  # MacOS arm64
  - project: 'libretro-infrastructure/ci-templates'
    file: 'osx-cmake-arm64.yml'

  ################################## CELLULAR ################################
  # Android
  - project: 'libretro-infrastructure/ci-templates'
    file: '/android-cmake.yml'

  # iOS arm64
  - project: 'libretro-infrastructure/ci-templates'
    file: '/ios-cmake.yml'

  # tvOS arm64
  - project: 'libretro-infrastructure/ci-templates'
    file: '/tvos-cmake.yml'

# Stages for building
stages:
  - build-prepare
  - build-shared

##############################################################################
#################################### STAGES ##################################
##############################################################################
#
################################### DESKTOPS #################################
# Windows 64-bit
libretro-build-windows-x64:
  extends:
    - .libretro-windows-cmake-x86_64
    - .core-defs
  image: $CI_SERVER_HOST:5050/libretro-infrastructure/libretro-build-mxe-win-cross-cores:mingw12
  variables:
    EXTRA_PATH: ../../Binary/x64
  before_script:
    - export NUMPROC=$(($(nproc)/5))
    - if builtin type -P ccache &> /dev/null; then ccache -V &> /dev/null; fi
    - mv /usr/lib/mxe/usr/x86_64-w64-mingw32.static/lib/libcurl.a .

# Linux 64-bit
libretro-build-linux-x64:
  extends:
    - .libretro-linux-cmake-x86_64
    - .core-defs
  image: $CI_SERVER_HOST:5050/libretro-infrastructure/libretro-build-amd64-ubuntu:backports
  variables:
    CC: /usr/bin/gcc-12
    CXX: /usr/bin/g++-12

# macOS Intel
libretro-build-osx-x64:
  tags:
    - mac-apple-silicon
  extends:
    - .libretro-osx-cmake-x86
    - .core-defs
  variables:
    CORE_ARGS: -DLIBRETRO=ON -DCMAKE_OSX_ARCHITECTURES=x86_64 -DCMAKE_SYSTEM_NAME=Darwin -DCMAKE_SYSTEM_PROCESSOR=x86_64

# macOS arm64
libretro-build-osx-arm64:
  extends:
    - .libretro-osx-cmake-arm64
    - .core-defs

################################### CELLULAR #################################
# Android ARMv8a
android-arm64-v8a:
  extends:
    - .libretro-android-cmake-arm64-v8a
    - .core-defs
  variables:
    ANDROID_NDK_VERSION: 26.2.11394342
    NDK_ROOT: /android-sdk-linux/ndk/$ANDROID_NDK_VERSION

# iOS arm64
libretro-build-ios-arm64:
  extends:
    - .libretro-ios-cmake-arm64
    - .core-defs
  variables:
    CMAKE_ADDL_COMP_FLAGS: ""
    IOS_MINVER: 14.0

# tvOS arm64
libretro-build-tvos-arm64:
  extends:
    - .libretro-tvos-cmake-arm64
    - .core-defs
  variables:
    CMAKE_ADDL_COMP_FLAGS: ""
    MINVER: 14.0
