name: Build Dolphin (libretro) on iOS

on: [push, pull_request]

env:
  core_id: dolphin_libretro

jobs:
  build:
    runs-on: macos-latest
    steps:
    - name: Install dependencies
      run: |
        brew update
        brew install cmake mbedtls zlib

    - name: Checkout Dolphin (libretro) repo
      uses: actions/checkout@v6
      with:
        path: ${{ env.core_id }}
        submodules: recursive

    - name: Configure (iOS arm64)
      run: |
        cd ${{ env.core_id }}
        cmake \
          -DCMAKE_BUILD_TYPE=Release \
          -DCMAKE_POSITION_INDEPENDENT_CODE=ON \
          -DCMAKE_C_FLAGS="" \
          -DCMAKE_CXX_FLAGS="" \
          -DIOS=ON \
          -DCMAKE_OSX_DEPLOYMENT_TARGET=14.0 \
          -DCMAKE_SYSTEM_NAME=iOS \
          -DCMAKE_SYSTEM_PROCESSOR=arm64 \
          -DCMAKE_OSX_ARCHITECTURES=arm64 \
          -DLIBRETRO=ON \
          . -Bbuild/ios-arm64

    - name: Build
      run: |
        cd ${{ env.core_id }}/build/ios-arm64
        make -j$(sysctl -n hw.ncpu)
